name: Cargo Test

on:
  push: 
    branches: 
      - master
  pull_request:
    branches:
      - master

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: light client project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo clippy
      - run: cargo fmt -- --check  
      - run: cargo test --verbose
  